// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	baseRoleFieldNames          = builder.RawFieldNames(&BaseRole{})
	baseRoleRows                = strings.Join(baseRoleFieldNames, ",")
	baseRoleRowsExpectAutoSet   = strings.Join(stringx.Remove(baseRoleFieldNames, "`id`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), ",")
	baseRoleRowsWithPlaceHolder = strings.Join(stringx.Remove(baseRoleFieldNames, "`id`", "`create_time`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`"), "=?,") + "=?"

	cacheAiopsSysBaseRoleIdPrefix   = "cache:aiopsSys:baseRole:id:"
	cacheAiopsSysBaseRoleNamePrefix = "cache:aiopsSys:baseRole:name:"
)

type (
	baseRoleModel interface {
		Insert(ctx context.Context, data *BaseRole) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*BaseRole, error)
		FindOneByName(ctx context.Context, name string) (*BaseRole, error)
		Update(ctx context.Context, data *BaseRole) error
		Delete(ctx context.Context, id int64) error
	}

	defaultBaseRoleModel struct {
		sqlc.CachedConn
		table string
	}

	BaseRole struct {
		Id       int64        `db:"id"`
		CreateBy string       `db:"create_by"`
		CreateAt time.Time    `db:"create_at"`
		UpdateBy string       `db:"update_by"`
		UpdateAt time.Time    `db:"update_at"`
		DeleteAt sql.NullTime `db:"delete_at"`
		Name     string       `db:"name"` // 角色名称
		Info     string       `db:"info"` // 描述信息
	}
)

func newBaseRoleModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultBaseRoleModel {
	return &defaultBaseRoleModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`base_role`",
	}
}

func (m *defaultBaseRoleModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	aiopsSysBaseRoleIdKey := fmt.Sprintf("%s%v", cacheAiopsSysBaseRoleIdPrefix, id)
	aiopsSysBaseRoleNameKey := fmt.Sprintf("%s%v", cacheAiopsSysBaseRoleNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, aiopsSysBaseRoleIdKey, aiopsSysBaseRoleNameKey)
	return err
}

func (m *defaultBaseRoleModel) FindOne(ctx context.Context, id int64) (*BaseRole, error) {
	aiopsSysBaseRoleIdKey := fmt.Sprintf("%s%v", cacheAiopsSysBaseRoleIdPrefix, id)
	var resp BaseRole
	err := m.QueryRowCtx(ctx, &resp, aiopsSysBaseRoleIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", baseRoleRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBaseRoleModel) FindOneByName(ctx context.Context, name string) (*BaseRole, error) {
	aiopsSysBaseRoleNameKey := fmt.Sprintf("%s%v", cacheAiopsSysBaseRoleNamePrefix, name)
	var resp BaseRole
	err := m.QueryRowIndexCtx(ctx, &resp, aiopsSysBaseRoleNameKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `name` = ? limit 1", baseRoleRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, name); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultBaseRoleModel) Insert(ctx context.Context, data *BaseRole) (sql.Result, error) {
	aiopsSysBaseRoleIdKey := fmt.Sprintf("%s%v", cacheAiopsSysBaseRoleIdPrefix, data.Id)
	aiopsSysBaseRoleNameKey := fmt.Sprintf("%s%v", cacheAiopsSysBaseRoleNamePrefix, data.Name)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, baseRoleRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CreateBy, data.UpdateBy, data.DeleteAt, data.Name, data.Info)
	}, aiopsSysBaseRoleIdKey, aiopsSysBaseRoleNameKey)
	return ret, err
}

func (m *defaultBaseRoleModel) Update(ctx context.Context, newData *BaseRole) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	aiopsSysBaseRoleIdKey := fmt.Sprintf("%s%v", cacheAiopsSysBaseRoleIdPrefix, data.Id)
	aiopsSysBaseRoleNameKey := fmt.Sprintf("%s%v", cacheAiopsSysBaseRoleNamePrefix, data.Name)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, baseRoleRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CreateBy, newData.UpdateBy, newData.DeleteAt, newData.Name, newData.Info, newData.Id)
	}, aiopsSysBaseRoleIdKey, aiopsSysBaseRoleNameKey)
	return err
}

func (m *defaultBaseRoleModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheAiopsSysBaseRoleIdPrefix, primary)
}

func (m *defaultBaseRoleModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", baseRoleRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultBaseRoleModel) tableName() string {
	return m.table
}
