// Code generated by goctl. DO NOT EDIT!

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	relUserTeamFieldNames          = builder.RawFieldNames(&RelUserTeam{})
	relUserTeamRows                = strings.Join(relUserTeamFieldNames, ",")
	relUserTeamRowsExpectAutoSet   = strings.Join(stringx.Remove(relUserTeamFieldNames, "`id`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`"), ",")
	relUserTeamRowsWithPlaceHolder = strings.Join(stringx.Remove(relUserTeamFieldNames, "`id`", "`update_at`", "`updated_at`", "`update_time`", "`create_at`", "`created_at`", "`create_time`"), "=?,") + "=?"

	cacheAiopsSysRelUserTeamIdPrefix           = "cache:aiopsSys:relUserTeam:id:"
	cacheAiopsSysRelUserTeamTeamIdUserIdPrefix = "cache:aiopsSys:relUserTeam:teamId:userId:"
	cacheAiopsSysRelUserTeamUserIdTeamIdPrefix = "cache:aiopsSys:relUserTeam:userId:teamId:"
)

type (
	relUserTeamModel interface {
		Insert(ctx context.Context, data *RelUserTeam) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*RelUserTeam, error)
		FindOneByTeamIdUserId(ctx context.Context, teamId int64, userId int64) (*RelUserTeam, error)
		FindOneByUserIdTeamId(ctx context.Context, userId int64, teamId int64) (*RelUserTeam, error)
		Update(ctx context.Context, data *RelUserTeam) error
		Delete(ctx context.Context, id int64) error
	}

	defaultRelUserTeamModel struct {
		sqlc.CachedConn
		table string
	}

	RelUserTeam struct {
		Id     int64 `db:"id"`
		UserId int64 `db:"user_id"`
		TeamId int64 `db:"team_id"`
	}
)

func newRelUserTeamModel(conn sqlx.SqlConn, c cache.CacheConf) *defaultRelUserTeamModel {
	return &defaultRelUserTeamModel{
		CachedConn: sqlc.NewConn(conn, c),
		table:      "`rel_user_team`",
	}
}

func (m *defaultRelUserTeamModel) Delete(ctx context.Context, id int64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	aiopsSysRelUserTeamIdKey := fmt.Sprintf("%s%v", cacheAiopsSysRelUserTeamIdPrefix, id)
	aiopsSysRelUserTeamTeamIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheAiopsSysRelUserTeamTeamIdUserIdPrefix, data.TeamId, data.UserId)
	aiopsSysRelUserTeamUserIdTeamIdKey := fmt.Sprintf("%s%v:%v", cacheAiopsSysRelUserTeamUserIdTeamIdPrefix, data.UserId, data.TeamId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, aiopsSysRelUserTeamIdKey, aiopsSysRelUserTeamTeamIdUserIdKey, aiopsSysRelUserTeamUserIdTeamIdKey)
	return err
}

func (m *defaultRelUserTeamModel) FindOne(ctx context.Context, id int64) (*RelUserTeam, error) {
	aiopsSysRelUserTeamIdKey := fmt.Sprintf("%s%v", cacheAiopsSysRelUserTeamIdPrefix, id)
	var resp RelUserTeam
	err := m.QueryRowCtx(ctx, &resp, aiopsSysRelUserTeamIdKey, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", relUserTeamRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRelUserTeamModel) FindOneByTeamIdUserId(ctx context.Context, teamId int64, userId int64) (*RelUserTeam, error) {
	aiopsSysRelUserTeamTeamIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheAiopsSysRelUserTeamTeamIdUserIdPrefix, teamId, userId)
	var resp RelUserTeam
	err := m.QueryRowIndexCtx(ctx, &resp, aiopsSysRelUserTeamTeamIdUserIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `team_id` = ? and `user_id` = ? limit 1", relUserTeamRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, teamId, userId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRelUserTeamModel) FindOneByUserIdTeamId(ctx context.Context, userId int64, teamId int64) (*RelUserTeam, error) {
	aiopsSysRelUserTeamUserIdTeamIdKey := fmt.Sprintf("%s%v:%v", cacheAiopsSysRelUserTeamUserIdTeamIdPrefix, userId, teamId)
	var resp RelUserTeam
	err := m.QueryRowIndexCtx(ctx, &resp, aiopsSysRelUserTeamUserIdTeamIdKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v interface{}) (i interface{}, e error) {
		query := fmt.Sprintf("select %s from %s where `user_id` = ? and `team_id` = ? limit 1", relUserTeamRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, userId, teamId); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultRelUserTeamModel) Insert(ctx context.Context, data *RelUserTeam) (sql.Result, error) {
	aiopsSysRelUserTeamIdKey := fmt.Sprintf("%s%v", cacheAiopsSysRelUserTeamIdPrefix, data.Id)
	aiopsSysRelUserTeamTeamIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheAiopsSysRelUserTeamTeamIdUserIdPrefix, data.TeamId, data.UserId)
	aiopsSysRelUserTeamUserIdTeamIdKey := fmt.Sprintf("%s%v:%v", cacheAiopsSysRelUserTeamUserIdTeamIdPrefix, data.UserId, data.TeamId)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, relUserTeamRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.UserId, data.TeamId)
	}, aiopsSysRelUserTeamIdKey, aiopsSysRelUserTeamTeamIdUserIdKey, aiopsSysRelUserTeamUserIdTeamIdKey)
	return ret, err
}

func (m *defaultRelUserTeamModel) Update(ctx context.Context, newData *RelUserTeam) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	aiopsSysRelUserTeamIdKey := fmt.Sprintf("%s%v", cacheAiopsSysRelUserTeamIdPrefix, data.Id)
	aiopsSysRelUserTeamTeamIdUserIdKey := fmt.Sprintf("%s%v:%v", cacheAiopsSysRelUserTeamTeamIdUserIdPrefix, data.TeamId, data.UserId)
	aiopsSysRelUserTeamUserIdTeamIdKey := fmt.Sprintf("%s%v:%v", cacheAiopsSysRelUserTeamUserIdTeamIdPrefix, data.UserId, data.TeamId)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, relUserTeamRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.UserId, newData.TeamId, newData.Id)
	}, aiopsSysRelUserTeamIdKey, aiopsSysRelUserTeamTeamIdUserIdKey, aiopsSysRelUserTeamUserIdTeamIdKey)
	return err
}

func (m *defaultRelUserTeamModel) formatPrimary(primary interface{}) string {
	return fmt.Sprintf("%s%v", cacheAiopsSysRelUserTeamIdPrefix, primary)
}

func (m *defaultRelUserTeamModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary interface{}) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", relUserTeamRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultRelUserTeamModel) tableName() string {
	return m.table
}
